/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* MCWDT_isr */
#define MCWDT_isr__INTC_CORTEXM4_ASSIGNED 1
#define MCWDT_isr__INTC_CORTEXM4_PRIORITY 7u
#define MCWDT_isr__INTC_NUMBER 19u
#define MCWDT_isr_INTC_CORTEXM4_ASSIGNED 1
#define MCWDT_isr_INTC_CORTEXM4_PRIORITY 7u
#define MCWDT_isr_INTC_NUMBER 19u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr_INTC_NUMBER 24u

/* UART_DEBUG_SCB_IRQ */
#define UART_DEBUG_SCB_IRQ__INTC_NUMBER 46u
#define UART_DEBUG_SCB_IRQ_INTC_NUMBER 46u

/* I2C_Pressure_SCB_IRQ */
#define I2C_Pressure_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_Pressure_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_Pressure_SCB_IRQ__INTC_NUMBER 43u
#define I2C_Pressure_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_Pressure_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_Pressure_SCB_IRQ_INTC_NUMBER 43u

/* ADC_Photoresistor_IRQ */
#define ADC_Photoresistor_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_Photoresistor_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_Photoresistor_IRQ__INTC_NUMBER 138u
#define ADC_Photoresistor_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_Photoresistor_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_Photoresistor_IRQ_INTC_NUMBER 138u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
