/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Alert_LED */
#define Alert_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_0_INBUF_ENABLED 0u
#define Alert_LED_0_INIT_DRIVESTATE 1u
#define Alert_LED_0_INIT_MUXSEL 0u
#define Alert_LED_0_INPUT_SYNC 2u
#define Alert_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_0_NUM 3u
#define Alert_LED_0_PORT GPIO_PRT6
#define Alert_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Alert_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_INBUF_ENABLED 0u
#define Alert_LED_INIT_DRIVESTATE 1u
#define Alert_LED_INIT_MUXSEL 0u
#define Alert_LED_INPUT_SYNC 2u
#define Alert_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_NUM 3u
#define Alert_LED_PORT GPIO_PRT6
#define Alert_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_DEBUG_rx */
#define UART_DEBUG_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_DEBUG_rx_0_INBUF_ENABLED 1u
#define UART_DEBUG_rx_0_INIT_DRIVESTATE 1u
#define UART_DEBUG_rx_0_INIT_MUXSEL 18u
#define UART_DEBUG_rx_0_INPUT_SYNC 2u
#define UART_DEBUG_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_rx_0_NUM 0u
#define UART_DEBUG_rx_0_PORT GPIO_PRT5
#define UART_DEBUG_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_DEBUG_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_DEBUG_rx_INBUF_ENABLED 1u
#define UART_DEBUG_rx_INIT_DRIVESTATE 1u
#define UART_DEBUG_rx_INIT_MUXSEL 18u
#define UART_DEBUG_rx_INPUT_SYNC 2u
#define UART_DEBUG_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_rx_NUM 0u
#define UART_DEBUG_rx_PORT GPIO_PRT5
#define UART_DEBUG_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_DEBUG_tx */
#define UART_DEBUG_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_DEBUG_tx_0_INBUF_ENABLED 0u
#define UART_DEBUG_tx_0_INIT_DRIVESTATE 1u
#define UART_DEBUG_tx_0_INIT_MUXSEL 18u
#define UART_DEBUG_tx_0_INPUT_SYNC 2u
#define UART_DEBUG_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_tx_0_NUM 1u
#define UART_DEBUG_tx_0_PORT GPIO_PRT5
#define UART_DEBUG_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_DEBUG_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_DEBUG_tx_INBUF_ENABLED 0u
#define UART_DEBUG_tx_INIT_DRIVESTATE 1u
#define UART_DEBUG_tx_INIT_MUXSEL 18u
#define UART_DEBUG_tx_INPUT_SYNC 2u
#define UART_DEBUG_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_tx_NUM 1u
#define UART_DEBUG_tx_PORT GPIO_PRT5
#define UART_DEBUG_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Disconnect_LED */
#define Disconnect_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_0_INBUF_ENABLED 0u
#define Disconnect_LED_0_INIT_DRIVESTATE 1u
#define Disconnect_LED_0_INIT_MUXSEL 0u
#define Disconnect_LED_0_INPUT_SYNC 2u
#define Disconnect_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_0_NUM 5u
#define Disconnect_LED_0_PORT GPIO_PRT0
#define Disconnect_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Disconnect_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_INBUF_ENABLED 0u
#define Disconnect_LED_INIT_DRIVESTATE 1u
#define Disconnect_LED_INIT_MUXSEL 0u
#define Disconnect_LED_INPUT_SYNC 2u
#define Disconnect_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_NUM 5u
#define Disconnect_LED_PORT GPIO_PRT0
#define Disconnect_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Advertising_LED */
#define Advertising_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_0_INBUF_ENABLED 0u
#define Advertising_LED_0_INIT_DRIVESTATE 1u
#define Advertising_LED_0_INIT_MUXSEL 0u
#define Advertising_LED_0_INPUT_SYNC 2u
#define Advertising_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_0_NUM 1u
#define Advertising_LED_0_PORT GPIO_PRT7
#define Advertising_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Advertising_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_INBUF_ENABLED 0u
#define Advertising_LED_INIT_DRIVESTATE 1u
#define Advertising_LED_INIT_MUXSEL 0u
#define Advertising_LED_INPUT_SYNC 2u
#define Advertising_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_NUM 1u
#define Advertising_LED_PORT GPIO_PRT7
#define Advertising_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_Pressure_scl */
#define I2C_Pressure_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_Pressure_scl_0_INBUF_ENABLED 1u
#define I2C_Pressure_scl_0_INIT_DRIVESTATE 1u
#define I2C_Pressure_scl_0_INIT_MUXSEL 19u
#define I2C_Pressure_scl_0_INPUT_SYNC 2u
#define I2C_Pressure_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_Pressure_scl_0_NUM 0u
#define I2C_Pressure_scl_0_PORT GPIO_PRT9
#define I2C_Pressure_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_Pressure_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_Pressure_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_Pressure_scl_INBUF_ENABLED 1u
#define I2C_Pressure_scl_INIT_DRIVESTATE 1u
#define I2C_Pressure_scl_INIT_MUXSEL 19u
#define I2C_Pressure_scl_INPUT_SYNC 2u
#define I2C_Pressure_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_Pressure_scl_NUM 0u
#define I2C_Pressure_scl_PORT GPIO_PRT9
#define I2C_Pressure_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_Pressure_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_Pressure_sda */
#define I2C_Pressure_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_Pressure_sda_0_INBUF_ENABLED 1u
#define I2C_Pressure_sda_0_INIT_DRIVESTATE 1u
#define I2C_Pressure_sda_0_INIT_MUXSEL 19u
#define I2C_Pressure_sda_0_INPUT_SYNC 2u
#define I2C_Pressure_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_Pressure_sda_0_NUM 1u
#define I2C_Pressure_sda_0_PORT GPIO_PRT9
#define I2C_Pressure_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_Pressure_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_Pressure_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_Pressure_sda_INBUF_ENABLED 1u
#define I2C_Pressure_sda_INIT_DRIVESTATE 1u
#define I2C_Pressure_sda_INIT_MUXSEL 19u
#define I2C_Pressure_sda_INPUT_SYNC 2u
#define I2C_Pressure_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_Pressure_sda_NUM 1u
#define I2C_Pressure_sda_PORT GPIO_PRT9
#define I2C_Pressure_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_Pressure_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* DATA_SoilMoisture */
#define DATA_SoilMoisture_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define DATA_SoilMoisture_0_INBUF_ENABLED 0u
#define DATA_SoilMoisture_0_INIT_DRIVESTATE 1u
#define DATA_SoilMoisture_0_INIT_MUXSEL 0u
#define DATA_SoilMoisture_0_INPUT_SYNC 2u
#define DATA_SoilMoisture_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DATA_SoilMoisture_0_NUM 1u
#define DATA_SoilMoisture_0_PORT GPIO_PRT10
#define DATA_SoilMoisture_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DATA_SoilMoisture_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DATA_SoilMoisture_DRIVEMODE CY_GPIO_DM_ANALOG
#define DATA_SoilMoisture_INBUF_ENABLED 0u
#define DATA_SoilMoisture_INIT_DRIVESTATE 1u
#define DATA_SoilMoisture_INIT_MUXSEL 0u
#define DATA_SoilMoisture_INPUT_SYNC 2u
#define DATA_SoilMoisture_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DATA_SoilMoisture_NUM 1u
#define DATA_SoilMoisture_PORT GPIO_PRT10
#define DATA_SoilMoisture_SLEWRATE CY_GPIO_SLEW_FAST
#define DATA_SoilMoisture_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* DATA_Photoresistor */
#define DATA_Photoresistor_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define DATA_Photoresistor_0_INBUF_ENABLED 0u
#define DATA_Photoresistor_0_INIT_DRIVESTATE 1u
#define DATA_Photoresistor_0_INIT_MUXSEL 0u
#define DATA_Photoresistor_0_INPUT_SYNC 2u
#define DATA_Photoresistor_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DATA_Photoresistor_0_NUM 0u
#define DATA_Photoresistor_0_PORT GPIO_PRT10
#define DATA_Photoresistor_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DATA_Photoresistor_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DATA_Photoresistor_DRIVEMODE CY_GPIO_DM_ANALOG
#define DATA_Photoresistor_INBUF_ENABLED 0u
#define DATA_Photoresistor_INIT_DRIVESTATE 1u
#define DATA_Photoresistor_INIT_MUXSEL 0u
#define DATA_Photoresistor_INPUT_SYNC 2u
#define DATA_Photoresistor_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DATA_Photoresistor_NUM 0u
#define DATA_Photoresistor_PORT GPIO_PRT10
#define DATA_Photoresistor_SLEWRATE CY_GPIO_SLEW_FAST
#define DATA_Photoresistor_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Hibernate_Wakeup_SW */
#define Hibernate_Wakeup_SW_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define Hibernate_Wakeup_SW_0_INBUF_ENABLED 1u
#define Hibernate_Wakeup_SW_0_INIT_DRIVESTATE 1u
#define Hibernate_Wakeup_SW_0_INIT_MUXSEL 0u
#define Hibernate_Wakeup_SW_0_INPUT_SYNC 2u
#define Hibernate_Wakeup_SW_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Hibernate_Wakeup_SW_0_NUM 4u
#define Hibernate_Wakeup_SW_0_PORT GPIO_PRT0
#define Hibernate_Wakeup_SW_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Hibernate_Wakeup_SW_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Hibernate_Wakeup_SW_DRIVEMODE CY_GPIO_DM_PULLUP
#define Hibernate_Wakeup_SW_INBUF_ENABLED 1u
#define Hibernate_Wakeup_SW_INIT_DRIVESTATE 1u
#define Hibernate_Wakeup_SW_INIT_MUXSEL 0u
#define Hibernate_Wakeup_SW_INPUT_SYNC 2u
#define Hibernate_Wakeup_SW_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Hibernate_Wakeup_SW_NUM 4u
#define Hibernate_Wakeup_SW_PORT GPIO_PRT0
#define Hibernate_Wakeup_SW_SLEWRATE CY_GPIO_SLEW_FAST
#define Hibernate_Wakeup_SW_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Data_Tempreature_Humidity */
#define Data_Tempreature_Humidity_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define Data_Tempreature_Humidity_0_INBUF_ENABLED 1u
#define Data_Tempreature_Humidity_0_INIT_DRIVESTATE 1u
#define Data_Tempreature_Humidity_0_INIT_MUXSEL 0u
#define Data_Tempreature_Humidity_0_INPUT_SYNC 2u
#define Data_Tempreature_Humidity_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Data_Tempreature_Humidity_0_NUM 6u
#define Data_Tempreature_Humidity_0_PORT GPIO_PRT5
#define Data_Tempreature_Humidity_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Data_Tempreature_Humidity_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Data_Tempreature_Humidity_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define Data_Tempreature_Humidity_INBUF_ENABLED 1u
#define Data_Tempreature_Humidity_INIT_DRIVESTATE 1u
#define Data_Tempreature_Humidity_INIT_MUXSEL 0u
#define Data_Tempreature_Humidity_INPUT_SYNC 2u
#define Data_Tempreature_Humidity_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Data_Tempreature_Humidity_NUM 6u
#define Data_Tempreature_Humidity_PORT GPIO_PRT5
#define Data_Tempreature_Humidity_SLEWRATE CY_GPIO_SLEW_FAST
#define Data_Tempreature_Humidity_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
